name: contact_x
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # Local DB
  shared_preferences: ^2.5.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Launcher Icon
  flutter_launcher_icons: ^0.14.4

  # Slidable for List Tile
  flutter_slidable: ^4.0.3

  # State Management
  get: ^4.7.3

  # other
  uuid: ^4.5.3
  flutter_phone_direct_caller: ^2.2.1
  flutter_contacts: ^1.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mocktail: ^1.0.5

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logos/logo.png"
  adaptive_icon_foreground: "assets/logos/logo.png"
  # adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 26

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
